CREATE INDEX mdl_files_pathnamehash_idx ON public.mdl_files USING btree (pathnamehash);
CREATE INDEX mdl_scorm_scoes_track_scormid_idx on mdl_scorm_scoes_track (scormid);
CREATE INDEX mdl_scorm_scoes_track_userid_idx on mdl_scorm_scoes_track (userid);
CREATE INDEX mdl_user_info_data_userid_fieldid_idx on mdl_user_info_data (userid, fieldid);
CREATE INDEX mdl_user_info_data_userid_idx on mdl_user_info_data (userid);
CREATE UNIQUE INDEX mdl_user_username_idx on mdl_user (username);
CREATE INDEX mdl_job_assignment_positionid_idx on mdl_job_assignment (positionid);
CREATE INDEX mdl_job_assignment_userid_idx on mdl_job_assignment (userid);
CREATE INDEX mdl_job_assignment_organisationid_idx on mdl_job_assignment (organisationid);
CREATE INDEX mdl_job_assignment_managerjaid_idx on mdl_job_assignment (managerjaid);
CREATE INDEX mdl_prog_user_assignment_userid_idx on mdl_prog_user_assignment (userid);
CREATE INDEX mdl_org_typeid_idx on mdl_org (typeid);
CREATE INDEX mdl_org_frameworkid_idx on mdl_org (frameworkid);
CREATE INDEX mdl_prog_completion_programid_userid_coursesetid_idx on mdl_prog_completion (programid,userid,coursesetid);
CREATE INDEX mdl_org_type_info_field_typeid_idx on mdl_org_type_info_field (typeid);
CREATE INDEX mdl_org_type_info_data_fieldid_organisationid_idx on mdl_org_type_info_data (fieldid,organisationid);
CREATE INDEX mdl_user_info_data_idx ON mdl_user_info_data (data);
CREATE INDEX mdl_user_info_field_defaultdata_idx ON mdl_user_info_field (defaultdata);
CREATE INDEX mdl_enrol_course_idx ON mdl_enrol(courseid);
CREATE INDEX mdl_role_assignments_contextid_component_itemid_userid_roleid ON mdl_role_assignments(contextid,component,itemid,userid,roleid);