-- Turn off Triggers
SET session_replication_role = replica;

drop table ips_temp_deleted_users;

CREATE TABLE ips_temp_deleted_users AS
  SELECT userid  from mdl_totara_userdata_user where
    timedeleted is not null
    and userid not in (2,75745,481574,740763,192748,1189325,1189327,1189328,1189329)
    and to_timestamp(timedeleted) <= DATE '2020-05-15';

delete from mdl_appraisal_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_appraisal_history';
delete from mdl_appraisal_role_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_appraisal_role_assignment';
delete from mdl_appraisal_scale where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_appraisal_scale';
delete from mdl_appraisal_user_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_appraisal_user_assignment';
delete from mdl_appraisal_user_event where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_appraisal_user_event';
delete from mdl_assign_grades where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assign_grades';
delete from mdl_assign_overrides where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assign_overrides';
delete from mdl_assign_submission where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assign_submission';
delete from mdl_assign_user_flags where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assign_user_flags';
delete from mdl_assign_user_mapping where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assign_user_mapping';
delete from mdl_assignfeedback_editpdf_quick where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assignfeedback_editpdf_quick';
delete from mdl_assignment_submissions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_assignment_submissions';
delete from mdl_auth_approved_request where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_auth_approved_request';
delete from mdl_auth_approved_request_snapshots where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_auth_approved_request_snapshots';
delete from mdl_auth_connect_sso_sessions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_auth_connect_sso_sessions';
delete from mdl_auth_connect_users where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_auth_connect_users';
delete from mdl_backup_controllers where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_backup_controllers';
delete from mdl_backup_trusted_files where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_backup_trusted_files';
delete from mdl_badge_backpack where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_badge_backpack';
delete from mdl_badge_criteria_met where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_badge_criteria_met';
delete from mdl_badge_issued where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_badge_issued';
delete from mdl_block_community where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_block_community';
delete from mdl_block_quicklinks where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_block_quicklinks';
delete from mdl_block_recent_activity where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_block_recent_activity';
delete from mdl_block_rss_client where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_block_rss_client';
delete from mdl_block_totara_featured_links_tiles where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_block_totara_featured_links_tiles';
delete from mdl_block_totara_stats where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_block_totara_stats';
delete from mdl_blog_external where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_blog_external';
delete from mdl_certif_completion where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_certif_completion';
delete from mdl_certif_completion_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_certif_completion_history';
delete from mdl_certificate_issues where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_certificate_issues';
delete from mdl_certificate_issues_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_certificate_issues_history';
delete from mdl_chat_messages where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_chat_messages';
delete from mdl_chat_messages_current where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_chat_messages_current';
delete from mdl_chat_users where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_chat_users';
delete from mdl_choice_answers where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_choice_answers';
delete from mdl_cohort_members where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_cohort_members';
delete from mdl_cohort_msg_queue where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_cohort_msg_queue';
delete from mdl_comments where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_comments';
delete from mdl_comp_criteria_record where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_comp_criteria_record';
delete from mdl_comp_record where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_comp_record';
delete from mdl_comp_record_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_comp_record_history';
delete from mdl_competency_plan where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_competency_plan';
delete from mdl_competency_usercomp where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_competency_usercomp';
delete from mdl_competency_usercompcourse where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_competency_usercompcourse';
delete from mdl_competency_usercompplan where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_competency_usercompplan';
delete from mdl_competency_userevidence where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_competency_userevidence';
delete from mdl_config_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_config_log';
delete from mdl_course_completion_crit_compl where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_course_completion_crit_compl';
delete from mdl_course_completion_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_course_completion_history';
delete from mdl_course_completion_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_course_completion_log';
delete from mdl_course_completions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_course_completions';
delete from mdl_course_modules_completion where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_course_modules_completion';
delete from mdl_data_records where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_data_records';
delete from mdl_dp_plan where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_dp_plan';
delete from mdl_dp_plan_evidence where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_dp_plan_evidence';
delete from mdl_editor_atto_autosave where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_editor_atto_autosave';
delete from mdl_enrol_flatfile where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_enrol_flatfile';
delete from mdl_enrol_lti_users where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_enrol_lti_users';
delete from mdl_enrol_paypal where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_enrol_paypal';
delete from mdl_enrol_totara_f2f_pending where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_enrol_totara_f2f_pending';
delete from mdl_epic_completion where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_epic_completion';
delete from mdl_event where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_event';
delete from mdl_event_subscriptions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_event_subscriptions';
delete from mdl_events_queue where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_events_queue';
delete from mdl_external_services_users where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_external_services_users';
delete from mdl_external_tokens where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_external_tokens';
delete from mdl_facetoface_interest where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_facetoface_interest';
delete from mdl_facetoface_notification_hist where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_facetoface_notification_hist';
delete from mdl_facetoface_notification_sent where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_facetoface_notification_sent';
delete from mdl_facetoface_session_roles where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_facetoface_session_roles';
delete from mdl_facetoface_signups where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_facetoface_signups';
delete from mdl_feedback360 where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback360';
delete from mdl_feedback360_resp_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback360_resp_assignment';
delete from mdl_feedback360_scale where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback360_scale';
delete from mdl_feedback360_user_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback360_user_assignment';
delete from mdl_feedback_completed where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback_completed';
delete from mdl_feedback_completed_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback_completed_history';
delete from mdl_feedback_completedtmp where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_feedback_completedtmp';
delete from mdl_files where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_files';
delete from mdl_forum_digests where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_digests';
delete from mdl_forum_discussion_subs where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_discussion_subs';
delete from mdl_forum_discussions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_discussions';
delete from mdl_forum_posts where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_posts';
delete from mdl_forum_queue where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_queue';
delete from mdl_forum_read where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_read';
delete from mdl_forum_subscriptions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_subscriptions';
delete from mdl_forum_track_prefs where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_forum_track_prefs';
delete from mdl_gap_aspirational where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_gap_aspirational';
delete from mdl_glossary_entries where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_glossary_entries';
delete from mdl_goal_personal where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_goal_personal';
delete from mdl_goal_record where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_goal_record';
delete from mdl_goal_user_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_goal_user_assignment';
delete from mdl_grade_grades where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_grade_grades';
delete from mdl_grade_grades_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_grade_grades_history';
delete from mdl_grade_import_values where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_grade_import_values';
delete from mdl_groups_members where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_groups_members';
delete from mdl_job_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_job_assignment';
delete from mdl_lesson_attempts where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_lesson_attempts';
delete from mdl_lesson_branch where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_lesson_branch';
delete from mdl_lesson_grades where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_lesson_grades';
delete from mdl_lesson_overrides where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_lesson_overrides';
delete from mdl_lesson_timer where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_lesson_timer';
delete from mdl_local_user_secondary_email where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_local_user_secondary_email';
delete from mdl_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_log';
delete from mdl_logstore_standard_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_logstore_standard_log';
delete from mdl_lti_submission where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_lti_submission';
delete from mdl_message_contacts where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_message_contacts';
delete from mdl_messageinbound_messagelist where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_messageinbound_messagelist';
delete from mdl_mnet_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_mnet_log';
delete from mdl_mnet_session where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_mnet_session';
delete from mdl_mnetservice_enrol_enrolments where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_mnetservice_enrol_enrolments';
delete from mdl_my_pages where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_my_pages';
delete from mdl_nra_examtranscript_data where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_nra_examtranscript_data';
delete from mdl_persistent_login where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_persistent_login';
delete from mdl_portfolio_instance_user where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_portfolio_instance_user';
delete from mdl_portfolio_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_portfolio_log';
delete from mdl_portfolio_tempdata where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_portfolio_tempdata';
delete from mdl_post where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_post';
delete from mdl_prog_completion where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_completion';
delete from mdl_prog_completion_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_completion_history';
delete from mdl_prog_completion_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_completion_log';
delete from mdl_prog_exception where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_exception';
delete from mdl_prog_extension where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_extension';
delete from mdl_prog_future_user_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_future_user_assignment';
delete from mdl_prog_messagelog where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_messagelog';
delete from mdl_prog_user_assignment where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_prog_user_assignment';
delete from mdl_question_attempt_steps where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_question_attempt_steps';
delete from mdl_quiz_attempts where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_quiz_attempts';
delete from mdl_quiz_grades where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_quiz_grades';
delete from mdl_quiz_overrides where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_quiz_overrides';
delete from mdl_rating where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_rating';
delete from mdl_reminder_sent where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_reminder_sent';
delete from mdl_report_builder_saved where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_report_builder_saved';
delete from mdl_report_builder_schedule where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_report_builder_schedule';
delete from mdl_report_builder_schedule_email_systemuser where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_report_builder_schedule_email_systemuser';
delete from mdl_reportbuilder_grp_user_record where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_reportbuilder_grp_user_record';
delete from mdl_reportbuilder_grp_user_user where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_reportbuilder_grp_user_user';
delete from mdl_repository_instances where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_repository_instances';
delete from mdl_role_assignments where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_role_assignments';
delete from mdl_role_sortorder where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_role_sortorder';
delete from mdl_scale where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_scale';
delete from mdl_scale_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_scale_history';
delete from mdl_scorm_aicc_session where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_scorm_aicc_session';
delete from mdl_scorm_scoes_track where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_scorm_scoes_track';
delete from mdl_sessions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_sessions';
delete from mdl_stats_user_daily where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_stats_user_daily';
delete from mdl_stats_user_monthly where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_stats_user_monthly';
delete from mdl_stats_user_weekly where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_stats_user_weekly';
delete from mdl_survey_analysis where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_survey_analysis';
delete from mdl_survey_answers where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_survey_answers';
delete from mdl_tag where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_tag';
delete from mdl_tool_monitor_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_tool_monitor_history';
delete from mdl_tool_monitor_rules where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_tool_monitor_rules';
delete from mdl_tool_monitor_subscriptions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_tool_monitor_subscriptions';
delete from mdl_tool_sitepolicy_user_consent where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_tool_sitepolicy_user_consent';
delete from mdl_totara_connect_sso_sessions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_totara_connect_sso_sessions';
delete from mdl_totara_dashboard_user where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_totara_dashboard_user';
delete from mdl_totara_userdata_export where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_totara_userdata_export';
delete from mdl_totara_userdata_purge where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_totara_userdata_purge';
delete from mdl_totara_userdata_user where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_totara_userdata_user';
delete from mdl_upgrade_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_upgrade_log';
delete from mdl_user_devices where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_devices';
delete from mdl_user_enrolments where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_enrolments';
delete from mdl_user_info_data where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_info_data';
delete from mdl_user_lastaccess where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_lastaccess';
delete from mdl_user_password_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_password_history';
delete from mdl_user_password_resets where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_password_resets';
delete from mdl_user_preferences where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_preferences';
delete from mdl_user_private_key where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_user_private_key';
delete from mdl_webex_completions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_webex_completions';
delete from mdl_webex_reminder_log where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_webex_reminder_log';
delete from mdl_webex_sessions_registration where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_webex_sessions_registration';
delete from mdl_webex_waitlist_signups where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_webex_waitlist_signups';
delete from mdl_wiki_locks where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_wiki_locks';
delete from mdl_wiki_pages where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_wiki_pages';
delete from mdl_wiki_subwikis where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_wiki_subwikis';
delete from mdl_wiki_versions where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_wiki_versions';
delete from mdl_workshop_aggregations where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_workshop_aggregations';
delete from mdl_workshop_assessments_old where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_workshop_assessments_old';
delete from mdl_workshop_comments_old where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_workshop_comments_old';
delete from mdl_workshop_submissions_old where userid in (select userid from ips_temp_deleted_users);
select  'deleted from mdl_workshop_submissions_old';
delete from wage_and_hour_history where userid in (select userid from ips_temp_deleted_users);
select  'deleted from wage_and_hour_history';

delete from mdl_user where id in (select userid from ips_temp_deleted_users);

SET session_replication_role = DEFAULT;