version: 0.2

phases:
 # install:
 # runtime-versions:
  #   php: 7.4
  build:
    commands:
      - npm install
  post_build:
    commands:
      - echo PWD
      - pwd
      - rm composer.*
      - zip -r output.zip * -x scripts/**\* config/**\* *.yml
artifacts:
  files:
    - output.zip
    - appspec.yml
    - scripts/**/*
    - config/**/*